Name:BILIKA MELODY
Reg.no: 2022/DCSE/011/ss
Date: 29 07 2022

Test one CS Maths

In [1]:
#IMPORTING LIBRARIES
import numpy as np
import pandas as pd
import random
import statistics

#no1
A

#no2
C

#no3
D

#no 4
A and D

#no5
C

#no6
B and D

#no7
C


#no8
A

#no9
D

In [ ]:
#no10, a
C

#10,b
2

In [2]:
import numpy as np

[]


In [12]:
import numpy as np

In [13]:
##no5
#no 5:1
X = np.array([[25, 2], [5, 26], [3, 7]])
z=np.shape(X)
print(z)

(3, 2)


In [14]:
#no5:2
c=np.transpose(X)
print(c)

[[25  5  3]
 [ 2 26  7]]


In [23]:
#no5:4
X = np.array([[25, 2], [5, 26], [3, 7]])
A = np.array([[3, 4], [5, 6], [7, 8]])
print(np.dot(X,A))      ##no of rows in X != to number of rows in A therefore

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [24]:
##NO6
#6a
m=np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(m)
mtm=np.dot(m.T,m)
mtminv=np.linalg.inv(m)
print(mtminv)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [25]:
#6b
m=np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(np.linalg.det(m))

0.2299999999999999


In [29]:
##no4
#4:1
X=np.array([25, 2, 5])
print(X)

[25  2  5]


In [30]:
#4:2
k=np.shape(X)
print(k)

(3,)


In [32]:
#4:3
v=np.transpose(X)
print(v)

[25  2  5]


In [ ]:
#4:4


In [43]:
##No2:1
#head=1
#tail=0
#coin tossed once=1
#probability of success is 0.5
n=1
p=0.5
z=np.random.binomial(n,p)
print(z)


0


In [41]:
#no2:2
